### ISSUE TITLE
Implementation on Razor Pages

### ISSUE THREAD

**Issue by gokujax** [michaelvs97/AspNetCore.ReCaptcha#10]
How to implement the package on Razor Pages using localhost?

**Comment by michaelvs97** [comment]
Hi Gokujax,

Please refer to the [`ReadMe`](https://github.com/michaelvs97/AspNetCore.ReCaptcha/blob/master/README.md), this covers how to setup the library. Please check the Usage section of the readme. Implementation is the same for both mvc as well as razor pages. 

Following this readme will also make sure this library works on localhost.

If you continue experience difficulties, feel free to contact me again.

**Comment by BrightSoul** [comment]
Hey @michaelvs97, thanks for this library, it makes reCaptcha very easy to use.
I'm joining @gokujax on his request to make this work on Razor Pages. Because, you see, the `ValidateReCaptcha` cannot be used on a page handler. It simply won't work as per the [documentation on the Authorize attribute](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-3.1&branch=pr-en-us-18879#authorize-attribute-and-razor-pages). You'll get a warning on compilation.
```
warning MVC1001: 'ValidateReCaptchaAttribute' cannot be applied to Razor Page handler methods. It may be applied either to the Razor Page model or applied globally.
```
Unfortunately, I cannot apply the `ValidateReCaptchaAttribute` attribute at the Razor Page model becuase it can only be applied on methods.
https://github.com/michaelvs97/AspNetCore.ReCaptcha/blob/754a9186b4182c17a216c9f676af758aacf8d089/AspNetCore.ReCaptcha/ValidateReCaptchaAttribute.cs#L11
However, thanks to your `IReCaptchaService`, I managed to find this workaround.
```csharp
[BindProperty(Name = "g-recaptcha-response")]
[Required]
public string RecaptchaResponse { get; set; }

public async Task<IActionResult> OnPostAsync([FromServices] IReCaptchaService service)
{
  if (!await service.Verify(RecaptchaResponse))
  {
    ModelState.AddModelError(string.Empty, "Captcha not solved");
  }

  if (ModelState.IsValid)
  {
     // Captcha was solved, do something meaningful
     return RedirectToPage();
  }
  return Page();
}
```

Please provide an 'official' sample for Razor Pages. I couldn't find it in the `Samples` directory.

**Comment by sleeuwen** [comment]
Hi BrightSoul,

Thanks for using the library, we tried to make it easy to use for all app models, but we mostly use mvc ourselves. We believed it would just work with razor pages but as you explained there are some differences we missed. I'm glad you found a way around it for now but this should really be handled in the library.

If I understand correctly, there are extra restrictions on `OnGet` and `OnPost` (and others) handlers in razor pages, that you cannot add ActionFilters on those methods but they should be added to the `PageModel` class.

I'll try to have a look at this tomorrow (I'm in UTC+1) and also add a razor pages sample to the sample projects. What I think we have to do is allow the [ValidateReCaptcha] on classes and if the request is a POST (or PUT/PATCH/DELETE?), require the recaptcha token to be set and validate it. The only thing with that is if there are multiple POST page handlers on the same model and only one should be validated, that's not possible. But from what I read at that point you are better off having multiple PageModel's.

If you have any other suggestions or if I missed something, please let me know.

**Comment by BrightSoul** [comment]
Hey @sleeuwen, thanks for your quick reply!

> you cannot add ActionFilters on those methods but they should be added to the PageModel class.
Yes, exactly. That's

> What I think we have to do is allow the [ValidateReCaptcha] on classes and if the request is a POST (or PUT/PATCH/DELETE?), require the recaptcha token to be set and validate it

I think that's the most quick and reasonable way to solve it, yes.

> But from what I read at that point you are better off having multiple PageModel's.
Indeed, and this is also Microsoft's advice on this issue, since it also affects the `Authorize` attribute. Read the a) option in this comment here:
https://github.com/dotnet/aspnetcore/issues/8737#issuecomment-611256317

> a) you could consider using separate pages
> b) you could write a filter that performs authorization as part of `IAsyncPageFilter.OnPageHandlerSelectionAsync`.

Maybe b) could also be a viable option. I've not examined the code so I'm not sure the amount of work it would require.
Thank you!

**Comment by sleeuwen** [comment]
Hi @BrightSoul,

We released version 1.2.0 of the library to nuget and should be available now.
With that you can set the `[ValidateReCaptcha]` attribute on your PageModel and it will validate all form submits.
I also added a sample for this [here](https://github.com/michaelvs97/AspNetCore.ReCaptcha/blob/master/Samples/AspNetCore.ReCaptcha.Net50/Pages/Home/Contact.cshtml.cs)

**Comment by gokujax** [comment]
Thanks a lot @sleeuwen 👍

**Comment by BrightSoul** [comment]
Amazing @sleeuwen, thanks 👍 I'm featuring this in my Udemy course on ASP.NET Core.
