### ISSUE TITLE
Interested in contributing

### ISSUE THREAD

**Issue by nwoolls** [michaelvs97/AspNetCore.ReCaptcha#54]
Hi there - apologies for nuking the template. Hopefully this inquiry is OK.

I'd like to contribute two features:

1. An "Enabled" property in the settings that defaults to `true` for backward compatibility. If `false`, the HTML would not be rendered and the action filter would not validate the submission. Note that it looks like this has also been requested here: https://github.com/michaelvs97/AspNetCore.ReCaptcha/issues/53
2. An `AutoTheme` property with corresponding `auto-theme=true` attribute in the tag helper. If true, inject a script that sets the theme to "dark" based on e.g. `window.matchMedia('(prefers-color-scheme: dark)').matches`

We're handling these in our application but it would be cleaner if implemented in the library.

If you are interested in these features I'd be happy to contribute. Let me know if the above implementations sound good and if I should then just stage two typical PRs into a `develop` branch or follow some other workflow.

**Comment by michaelvs97** [comment]
Heya @nwoolls,

Sorry for the somewhat late response, it has been quite some busy weeks.
The inquiry is fine. The features you are mentioning sound very nice to have in the library. We are happy for you to collaborate on this project and implement these features.

You can follow the following flow in order to be able to add to the repository:
- Create a feature branch per feature you would like to add to the project.
- Make sure you update any test cases (if applicable)
- Create a PR for your functionality towards master
- Please add a short description in your pull request in order to describe what the intended behavior is that you are changing
- We'll do a code review, and your feature can be merged to master 🥳 

Thanks for thinking along and coming up with such neat ideas for the project. We are looking forward to the pull requests!

Have a wonderful evening,
Michael

**Comment by nwoolls** [comment]
@michaelvs97 thanks for the guidance - two PRs are ready when you are.
