### ISSUE TITLE
Make it async?

### ISSUE THREAD

**Issue by mdima** [michaelvs97/AspNetCore.ReCaptcha#60]
**Is your feature request related to a problem? Please describe.**
Hello, this plugin is great, just it lowers my "PageSpeed" score a lot. 
I am talking about the Recaptcha v3. 

**Describe the solution you'd like**
If the <script> tag that calls the Recaptha function is "async" (or better: defer) the issue does not occur. 

Thanks!

**Comment by sleeuwen** [comment]
Hi @mdima , 

Thanks for the suggestion, unfortunately this is currently not possible as an inline script is generated for V3, and inline script's can be marked async or defer. Also, the inline script has to run after the recaptcha js has loaded, so we also can't mark the library as defer/async, because then the inline script won't work.

The V2 and V2 Invisible options already have `defer` in their script tags.
